"use strict";
var chovendo = false;
var nome = "Felipe";
var idade = 32;
var listaDePessoas = [new Date, new Date];
var tecnologias = ['html', 'css', 'js'];
var notas = [0, 1, 2, 3, 4, 5];
var tupla = ["gian", true, 27];
var uniontype = 25;
var object = new Date;
var curso = 'front-end';
